config/routes.rb
Rails.application.routes.draw do

  resources :marathons

  root 'welcome#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/marathon.rb
class Marathon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/marathons_controller.rb
class MarathonsController < ApplicationController
  before_action :set_marathon, only: [:show, :edit, :update, :destroy]

  # GET /marathons
  # GET /marathons.json
  def index
    @marathons = Marathon.all
  end

  # GET /marathons/1
  # GET /marathons/1.json
  def show
  end

  # GET /marathons/new
  def new
    @marathon = Marathon.new
  end

  # GET /marathons/1/edit
  def edit
  end

  # POST /marathons
  # POST /marathons.json
  def create
    @marathon = Marathon.new(marathon_params)

    respond_to do |format|
      if @marathon.save
        flash[:success] = "#{@marathon.name} was successfully created."
        format.html { redirect_to marathons_url}
        format.json { render :show, status: :created, location: @marathon }
      else
        format.html { render :new }
        format.json { render json: @marathon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marathons/1
  # PATCH/PUT /marathons/1.json
  def update
    respond_to do |format|
      if @marathon.update(marathon_params)

        flash[:success] = "#{@marathon.name} was successfully updated."
        format.html { redirect_to @marathon}
        format.json { render :show, status: :ok, location: @marathon }
      else
        format.html { render :edit }
        format.json { render json: @marathon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marathons/1
  # DELETE /marathons/1.json
  def destroy
    @marathon.destroy
    respond_to do |format|
      flash[:alert] = '#{@marathon.name} was successfully destroyed.'
      format.html { redirect_to marathons_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marathon
      @marathon = Marathon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marathon_params
      params.require(:marathon).permit(:name, :description, :event_date, :city, :state, :country, :registration_url, :website_url, :logo, :image, :map)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert-info"
    when 'success' then "alert-success"
    when 'error' then "alert-danger"
    when 'alert' then "alert-warning"
    end
  end
end

app/helpers/marathons_helper.rb
module MarathonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert alert-dismissable <%= flash_class(key) %> fade in">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MarathonKit</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag('application') %>

  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/flash_messages' %>
	<div class="container-fluid">

<%= yield %>

	</div>
</body>
</html>

app/views/marathons/_form.html.erb
<%= form_for(@marathon) do |f| %>
  <% if @marathon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marathon.errors.count, "error") %> prohibited this marathon from being saved:</h2>

      <ul>
      <% @marathon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :registration_url %><br>
    <%= f.text_field :registration_url %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :map %><br>
    <%= f.text_field :map %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marathons/edit.html.erb
<h1>Editing marathon</h1>

<%= render 'form' %>

<%= link_to 'Show', @marathon %> |
<%= link_to 'Back', marathons_path %>

app/views/marathons/index.html.erb
<h1>All Marathons</h1>

<table class ="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Event date</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Registration url</th>
      <th>Website url</th>
      <th>Logo</th>
      <th>Image</th>
      <th>Map</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="">
    <% @marathons.each do |marathon| %>
      <tr>
        <td><%= marathon.name %></td>
        <td><%= marathon.description %></td>
        <td><%= marathon.event_date %></td>
        <td><%= marathon.city %></td>
        <td><%= marathon.state %></td>
        <td><%= marathon.country %></td>
        <td><%= marathon.registration_url %></td>
        <td><%= marathon.website_url %></td>
        <td><%= marathon.logo %></td>
        <td><%= marathon.image %></td>
        <td><%= marathon.map %></td>
        <td><%= link_to 'Show', marathon %></td>
        <td><%= link_to 'Edit', edit_marathon_path(marathon) %></td>
        <td><%= link_to 'Destroy', marathon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marathon', new_marathon_path %>

app/views/marathons/new.html.erb
<h1>New marathon</h1>

<%= render 'form' %>

<%= link_to 'Back', marathons_path %>

app/views/marathons/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @marathon.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @marathon.description %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @marathon.event_date %>
</p>

<p>
  <strong>City:</strong>
  <%= @marathon.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @marathon.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @marathon.country %>
</p>

<p>
  <strong>Registration url:</strong>
  <%= @marathon.registration_url %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @marathon.website_url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @marathon.logo %>
</p>

<p>
  <strong>Image:</strong>
  <%= @marathon.image %>
</p>

<p>
  <strong>Map:</strong>
  <%= @marathon.map %>
</p>

<%= link_to 'Edit', edit_marathon_path(@marathon) %> |
<%= link_to 'Back', marathons_path %>

app/views/welcome/index.html.erb
<h1>This is Where is all Beginsss</h1>
<p>Hello from Index</p>

<a href="/demo/hello" class="glyphicon glyphicon-volume-down">Hello Page 1</a><br />
<%= link_to('Hello Page 2', {:action => 'hello'}) %> <br />

<%= link_to('Hello with Parameters', {:action => 'hello', :page => 5, :id => 20}) %>


<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Get the Marathon Kit
</button> 

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Download the Marathon Kit</h4>
      </div>
      <div class="modal-body">
        Optin Form goes here
      </div>
      <div class="modal-footer">
      	<button type="button" class="btn btn-success">Download Now</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div> 


<div id="rootwizard">
					<div class="navbar">
					  <div class="navbar-inner">
					    <div class="container">
					<ul>
					  	<li><a href="#tab1" data-toggle="tab">When is your Marathon?</a></li>
						<li><a href="#tab2" data-toggle="tab">What is your Current Pace?</a></li>
						<li><a href="#tab3" data-toggle="tab">What is your target pace?</a></li>
						<li><a href="#tab4" data-toggle="tab">Finished!?</a></li>

					</ul>
					 </div>
					  </div>
					</div>
					<div id="bar" class="progress progress-striped active">
					  <div class="bar progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"></div>
					</div>
					<div class="tab-content">
					    <div class="tab-pane" id="tab1">
					      Step 1
					    </div>
					    <div class="tab-pane" id="tab2">
					      Step 2
					    </div>
						<div class="tab-pane" id="tab3">
							Step 3
					    </div>
					    <div class="tab-pane" id="tab4">
							F
					    </div>

						<ul class="pager wizard">
							<li class="previous first" style="display:none;"><a href="#">First</a></li>
							<li class="previous"><a href="#">Previous</a></li>
							<li class="next last" style="display:none;"><a href="#">Last</a></li>
						  	<li class="next"><a href="#">Next</a></li>
						</ul>
					</div>	
				</div> 